[[main]]
name = "Home"
url = ""
weight = -110

[[main]]
name = "Posts"
url = "post/"
weight = -108

[[main]]
name = "Projects"
url = "project/"
weight = -107


# [[main]]
# name = "Archives"
# url = "archive/"
# weight = -106

# [[main]]
# name = "Publications"
# url = "post/"
# weight = -109

[[main]]
name = "About"
url = "about/"
weight = -100


# [[main]]
#   name = "Archives"
#   url = "post/rich-content/"
#   weight = -109

# Submenus are done this way: parent -> identifier
# [[main]]
#   name = "Links"
#   identifier = "Links"
#   weight = -108
# [[main]]
#   parent = "Links"
#   name = "LinkedIn"
#   url = "https://www.linkedin.com/"
# [[main]]
#   parent = "Links"
#   name = "Twitter"
#   url = "https://twitter.com/"


# social menu links

[[social]]
name = "github"
type = "social"
weight = 1
url = "https://github.com/roshankarande"
[[social]]
name = "twitter"
weight = 2
url = "https://twitter.com/karande_roshan"
[[social]]
name = "linkedin"
weight = 3
url = "https://www.linkedin.com/in/roshan-karande-196b45a1/"
[[social]]
name = "rss"
weight = 4
url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
